# Generated by Django 5.1.7 on 2026-08-12 22:46

import django.db.models.deletion
from django.db import migrations, models


CITIES = (
    {
        'name': 'Москва', 'region_code': '77', 'region_label': 'Москва',
        'latitude': '55.755864', 'longitude': '37.617698',
        'geodata_source': 'OpenStreetMap contributors / seed_demo',
        'source_url': 'https://www.openstreetmap.org/?mlat=55.755864&mlon=37.617698#map=12/55.755864/37.617698',
        'location_verified': True, 'map_region_code': '50',
    },
    {
        'name': 'Екатеринбург', 'region_code': '66', 'region_label': 'Свердловская область',
        'latitude': '56.838011', 'longitude': '60.597465',
        'geodata_source': 'OpenStreetMap contributors / seed_demo',
        'source_url': 'https://www.openstreetmap.org/?mlat=56.838011&mlon=60.597465#map=12/56.838011/60.597465',
        'location_verified': True, 'map_region_code': '66',
    },
    {
        'name': 'Новосибирск', 'region_code': '54', 'region_label': 'Новосибирская область',
        'latitude': '55.030204', 'longitude': '82.920430',
        'geodata_source': 'OpenStreetMap contributors / seed_demo',
        'source_url': 'https://www.openstreetmap.org/?mlat=55.030204&mlon=82.920430#map=12/55.030204/82.920430',
        'location_verified': True, 'map_region_code': '54',
    },
)


def add_cities(apps, schema_editor):
    City = apps.get_model('events', 'City')
    Event = apps.get_model('events', 'Event')
    for data in CITIES:
        city_data = {
            key: value for key, value in data.items()
            if key not in {'map_region_code', 'region_code', 'name'}
        }
        city, _ = City.objects.get_or_create(
            region_code=data['region_code'],
            name=data['name'],
            defaults=city_data,
        )
        Event.objects.filter(
            region_code=data['map_region_code'],
            city__iexact=data['name'],
        ).update(city_ref=city, region_code=data['region_code'], region_label=data['region_label'])


def remove_cities(apps, schema_editor):
    City = apps.get_model('events', 'City')
    Event = apps.get_model('events', 'Event')
    Event.objects.filter(city_ref__name__in=[city['name'] for city in CITIES]).update(city_ref=None)
    City.objects.filter(
        geodata_source='OpenStreetMap contributors / seed_demo',
        name__in=[city['name'] for city in CITIES],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_merge_composite_regions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, editable=False, max_length=120, verbose_name='Город'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Город')),
                ('region_code', models.CharField(max_length=3, verbose_name='Код субъекта')),
                ('region_label', models.CharField(editable=False, max_length=160, verbose_name='Субъект РФ')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('geodata_source', models.CharField(max_length=160, verbose_name='Источник геоданных')),
                ('source_url', models.URLField(verbose_name='Ссылка на источник')),
                ('location_verified', models.BooleanField(default=False, verbose_name='Точка проверена')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('region_code', 'name'), name='unique_city_per_region')],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.city', verbose_name='Город'),
        ),
        migrations.RunPython(add_cities, remove_cities),
    ]
