# Generated by Django 5.2.15 on 2026-08-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_city_city_event_city_ref'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['published', 'ends_at', 'starts_at'], name='event_public_dates_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['region_code', 'published', 'ends_at'], name='event_region_public_idx'),
        ),
        migrations.AddIndex(
            model_name='eventsubmission',
            index=models.Index(fields=['status', 'created_at'], name='submission_status_idx'),
        ),
    ]
