import * as THREE from 'three';
import { SVGLoader } from 'three/addons/loaders/SVGLoader.js';
import { colorForRegion } from './regions';
import type { Region } from './regions';
import './style.css';

type CtfEvent = { id:number; title:string; regionCode:string; regionName:string; city:string; venue:string; startsAt:string; endsAt:string; format:string; description:string; website:string; organizer:string };
type RegionMesh = THREE.Mesh<THREE.ExtrudeGeometry, THREE.MeshStandardMaterial> & { userData:{ region:Region; targetLift:number; outline?:THREE.Line<THREE.BufferGeometry, THREE.LineBasicMaterial> } };

function el<T extends Element>(selector:string):T { const node=document.querySelector<T>(selector); if(!node) throw new Error(`Missing ${selector}`); return node; }
function escapeHtml(value:string):string { const node=document.createElement('span'); node.textContent=value; return node.innerHTML; }
function getCookie(name:string):string { return document.cookie.split(';').map(v=>v.trim()).find(v=>v.startsWith(`${name}=`))?.slice(name.length+1) ?? ''; }

const stage=el<HTMLElement>('#map-stage'), markersRoot=el<HTMLElement>('#event-markers');
const panel=el<HTMLElement>('#region-panel'), panelTitle=el<HTMLElement>('#panel-title'), panelKicker=el<HTMLElement>('#panel-kicker'), panelContent=el<HTMLElement>('#panel-content');
const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
const scene=new THREE.Scene(), camera=new THREE.PerspectiveCamera(26,1,.1,100); camera.position.set(0,-5.7,30); camera.lookAt(0,0,-.35);
const compactDevice=matchMedia('(max-width: 760px)').matches||((navigator.hardwareConcurrency??8)<=4);
const renderer=new THREE.WebGLRenderer({antialias:!compactDevice,alpha:true,powerPreference:'high-performance'}); renderer.setPixelRatio(Math.min(devicePixelRatio,compactDevice?1:1.25)); renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.shadowMap.enabled=false; renderer.domElement.className='map-stage__canvas'; stage.append(renderer.domElement);
const mapGroup=new THREE.Group(), mapViewport=new THREE.Group(); mapGroup.rotation.set(-.065,0,0); scene.add(mapViewport); mapViewport.add(mapGroup);
scene.add(new THREE.HemisphereLight(0xd6efff,0x061035,2.45));
const light=new THREE.DirectionalLight(0xe9f8ff,4.6); light.position.set(-8,-7,15); scene.add(light);
const rim=new THREE.DirectionalLight(0x607cff,2.2); rim.position.set(12,4,10); scene.add(rim);
const shadow=new THREE.Mesh(new THREE.PlaneGeometry(29,17),new THREE.MeshBasicMaterial({color:0x020719,transparent:true,opacity:.3,depthWrite:false})); shadow.position.z=-.74; mapViewport.add(shadow);
const silhouetteMaterial=new THREE.MeshStandardMaterial({color:0x10265c,roughness:.78,transparent:true,opacity:.65,depthWrite:false,side:THREE.DoubleSide});
const meshes:RegionMesh[]=[], meshById=new Map<string,RegionMesh[]>(), regionsById=new Map<string,Region>(), regionCenters=new Map<string,THREE.Vector3>();
const raycaster=new THREE.Raycaster(), pointer=new THREE.Vector2(), mapPlane=new THREE.Plane(new THREE.Vector3(0,0,1),0), targetPosition=new THREE.Vector3();
let events:CtfEvent[]=[], markerElements:HTMLElement[]=[], selectedId:string|null=null, hoveredId:string|null=null, ready=false, zoom=1, targetZoom=1, pointerDown=false, panning=false, pointerStart=new THREE.Vector2(), panAnchor:THREE.Vector3|null=null;

function setZoom(value:number,anchor:THREE.Vector3|null=null){const next=THREE.MathUtils.clamp(value,.72,3.2);if(anchor){const local=anchor.clone().sub(targetPosition).multiplyScalar(1/targetZoom);targetPosition.copy(anchor).addScaledVector(local,-next)}targetZoom=next;}
function resetViewport(){targetZoom=1;targetPosition.set(0,0,0)}
function renderSelection(){meshes.forEach(mesh=>{const active=mesh.userData.region.id===selectedId, hover=mesh.userData.region.id===hoveredId, base=new THREE.Color(mesh.userData.region.color);mesh.userData.targetLift=hover?0.76:active?0.28:0;mesh.material.color.copy(base);mesh.material.emissive.copy(base).multiplyScalar(.03);if(active){mesh.material.color.lerp(new THREE.Color(0xcff9ff),.55);mesh.material.emissive.set(0x62eaff).multiplyScalar(.35)}if(hover){mesh.material.color.lerp(new THREE.Color(0x00e5ff),.7);mesh.material.emissive.set(0x00d8ff).multiplyScalar(.72)}if(mesh.userData.outline){mesh.userData.outline.material.color.set(hover?0xffffff:active?0xbffaff:0x69bde9);mesh.userData.outline.material.opacity=hover?1:active?0.95:0.42}})}
function selectRegion(id:string){selectedId=id;renderSelection();renderRegionPanel(id);stage.setAttribute('aria-label',`Выбран регион: ${regionsById.get(id)?.name}`);history.replaceState(null,'',`#region=${id}`)}
function focusRegion(id:string){const list=meshById.get(id), center=regionCenters.get(id), viewportCenter=getWorldPoint(innerWidth/2,innerHeight/2);if(!list?.length||!center||!viewportCenter)return;const bounds=new THREE.Box3();list.forEach(m=>{m.geometry.computeBoundingBox();if(m.geometry.boundingBox)bounds.union(m.geometry.boundingBox)});const size=bounds.getSize(new THREE.Vector3()), regionZoom=THREE.MathUtils.clamp(5.3/Math.max(size.x,size.y),1.15,1.75);targetZoom=regionZoom;targetPosition.copy(viewportCenter).addScaledVector(center,-regionZoom)}
function normalizeMap(){const bounds=new THREE.Box3().setFromObject(mapGroup),center=bounds.getCenter(new THREE.Vector3()),size=bounds.getSize(new THREE.Vector3()),scale=22.5/Math.max(size.x,size.y);mapGroup.scale.set(scale,-scale,scale);mapGroup.position.set(-center.x*scale,center.y*scale+.62,0)}
function addRegion(id:string,name:string,paths:THREE.ShapePath[]){const region={id,name,fragments:paths.length,color:colorForRegion(id)};regionsById.set(id,region);const list:RegionMesh[]=[];paths.forEach(path=>SVGLoader.createShapes(path).forEach(shape=>{const geometry=new THREE.ExtrudeGeometry(shape,{depth:16,bevelEnabled:!compactDevice,bevelSegments:1,bevelSize:.32,bevelThickness:.38,curveSegments:1});geometry.translate(0,0,-16);const material=new THREE.MeshStandardMaterial({color:region.color,roughness:.58,metalness:.08,emissive:new THREE.Color(region.color).multiplyScalar(.035),side:THREE.DoubleSide});const mesh=new THREE.Mesh(geometry,material) as RegionMesh;mesh.userData={region,targetLift:0};const points=shape.getPoints(1).map(p=>new THREE.Vector3(p.x,p.y,.012));if(points.length>2){points.push(points[0].clone());const outline=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:0x69bde9,transparent:true,opacity:.42}));mesh.add(outline);mesh.userData.outline=outline}mapGroup.add(mesh);meshes.push(mesh);list.push(mesh)}));if(list.length)meshById.set(id,list)}
function translate(paths:THREE.ShapePath[],transform:string){const [x=0,y=0]=transform.match(/-?\d+(?:\.\d+)?/g)?.map(Number)??[0,0];paths.forEach(path=>path.subPaths.forEach(sub=>{sub.currentPoint.add(new THREE.Vector2(x,y));sub.curves.forEach(raw=>{const c=raw as THREE.Curve<THREE.Vector2>&{v0?:THREE.Vector2;v1?:THREE.Vector2;v2?:THREE.Vector2;v3?:THREE.Vector2;aX?:number;aY?:number};[c.v0,c.v1,c.v2,c.v3].forEach(p=>p?.add(new THREE.Vector2(x,y)));if(c.aX!==undefined)c.aX+=x;if(c.aY!==undefined)c.aY+=y})}));return paths}
function addSilhouette(data:string){if(!data)return;new SVGLoader().parse(`<svg xmlns="http://www.w3.org/2000/svg"><path d="${data}"/></svg>`).paths.forEach(p=>SVGLoader.createShapes(p).forEach(shape=>{const geometry=new THREE.ExtrudeGeometry(shape,{depth:.18,bevelEnabled:false});geometry.translate(0,0,-.7);mapGroup.add(new THREE.Mesh(geometry,silhouetteMaterial))}))}
async function loadMap(){stage.classList.add('is-loading');try{const text=await fetch('/static/map/russia-regions.svg').then(r=>{if(!r.ok)throw Error('Map unavailable');return r.text()}),doc=new DOMParser().parseFromString(text,'image/svg+xml'),loader=new SVGLoader();[...doc.querySelectorAll<SVGGElement>('svg > g[id^="region-"]')].forEach(group=>{const id=group.id.replace('region-',''), paths=[...group.querySelectorAll('path')].flatMap(p=>loader.parse(`<svg xmlns="http://www.w3.org/2000/svg"><path d="${p.getAttribute('d')??''}"/></svg>`).paths);addRegion(id,group.dataset.name??id,group.getAttribute('transform')?translate(paths,group.getAttribute('transform')!):paths)});normalizeMap();addSilhouette(doc.querySelector('#country-silhouette')?.getAttribute('d')??'');meshById.forEach((list,id)=>{const bounds=new THREE.Box3();list.forEach(m=>{m.geometry.computeBoundingBox();if(m.geometry.boundingBox)bounds.union(m.geometry.boundingBox)});regionCenters.set(id,bounds.getCenter(new THREE.Vector3()))});populateRegions();ready=true;const initial=new URLSearchParams(location.hash.slice(1)).get('region');if(initial&&meshById.has(initial))selectRegion(initial);renderMarkers()}catch(error){console.error(error);stage.setAttribute('aria-label','Не удалось загрузить карту')}finally{stage.classList.remove('is-loading')}}

function daysUntil(date:string){return Math.max(0,(new Date(date).getTime()-Date.now())/86400000)}
function dateText(date:string){return new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'}).format(new Date(date))}
function pulseClass(event:CtfEvent){const days=daysUntil(event.startsAt);return days<=3?'marker--hot':days<=14?'marker--soon':'marker--calm'}
function renderMarkers(){markersRoot.replaceChildren();markerElements=[];const nearest=new Map<string,CtfEvent>();events.forEach(event=>{if(!nearest.has(event.regionCode))nearest.set(event.regionCode,event)});nearest.forEach(event=>{if(!regionCenters.has(event.regionCode))return;const button=document.createElement('button');button.className=`event-marker ${pulseClass(event)}`;button.type='button';button.dataset.region=event.regionCode;button.setAttribute('aria-label',`${event.title}, ${event.regionName}, ${dateText(event.startsAt)}`);button.innerHTML=`<span class="event-marker__pulse"></span><span class="event-marker__flag">⚑</span><span class="event-marker__label">${nearestLabel(event)}</span>`;button.addEventListener('click',e=>{e.stopPropagation();openEvent(event)});markersRoot.append(button);markerElements.push(button)})}
function nearestLabel(event:CtfEvent){const days=Math.ceil(daysUntil(event.startsAt));return days<=0?'Сегодня':days===1?'Завтра':`через ${days} дн.`}
function positionMarkers(){markerElements.forEach(marker=>{const center=regionCenters.get(marker.dataset.region??'');if(!center)return;const point=center.clone();mapGroup.localToWorld(point);point.project(camera);const visible=point.z<1;marker.style.transform=`translate3d(${(point.x*.5+.5)*innerWidth}px, ${(-point.y*.5+.5)*innerHeight}px, 0)`;marker.hidden=!visible})}
async function loadEvents(){try{const response=await fetch('/api/events/'),data=await response.json();events=data.events;el('#event-count').textContent=events.length?`${events.length} ближайших CTF`:'Добавьте первый CTF';renderMarkers();if(selectedId)renderRegionPanel(selectedId)}catch{el('#event-count').textContent='События временно недоступны'}}
function renderRegionPanel(id:string){const region=regionsById.get(id);if(!region)return;const items=events.filter(e=>e.regionCode===id);panel.classList.add('is-open');panelKicker.textContent='ВЫБРАННЫЙ РЕГИОН';panelTitle.textContent=region.name;panelContent.innerHTML=items.length?`<p class="panel-count">${items.length} ${items.length===1?'ближайшее событие':'ближайших события'}</p><div class="event-list">${items.map(eventCard).join('')}</div>`:`<div class="empty-state"><span>⚑</span><h3>Пока тихо</h3><p>В этом регионе нет опубликованных CTF. Знаете о событии?</p><button class="button button--ghost" id="empty-suggest">Предложить CTF</button></div>`;panel.querySelectorAll<HTMLElement>('[data-event]').forEach(node=>node.addEventListener('click',()=>openEvent(events.find(e=>e.id===Number(node.dataset.event))!)));panel.querySelector('#empty-suggest')?.addEventListener('click',openSuggest)}
function closeRegionPanel(){panel.classList.remove('is-open');selectedId=null;hoveredId=null;resetViewport();renderSelection();stage.setAttribute('aria-label','Интерактивная карта регионов России. Выберите регион.');history.replaceState(null,'',location.pathname+location.search);stage.focus({preventScroll:true})}
function eventCard(e:CtfEvent){return `<button class="event-card" data-event="${e.id}" type="button"><span class="event-card__date">${new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'short'}).format(new Date(e.startsAt))}</span><span><strong>${escapeHtml(e.title)}</strong><small>${escapeHtml(e.city||e.format)} · ${dateText(e.startsAt)}</small></span><b>→</b></button>`}
function openEvent(e:CtfEvent){const modal=el<HTMLDialogElement>('#event-modal');el('#event-modal-content').innerHTML=`<p class="eyebrow">${escapeHtml(e.regionName)} · ${escapeHtml(e.format)}</p><h2 id="event-modal-title">${escapeHtml(e.title)}</h2><div class="event-meta"><div><span>СТАРТ</span><strong>${dateText(e.startsAt)}</strong></div><div><span>МЕСТО</span><strong>${escapeHtml([e.city,e.venue].filter(Boolean).join(', ')||'Онлайн')}</strong></div></div><p class="event-description">${escapeHtml(e.description)}</p>${e.organizer?`<p class="organizer">Организатор: ${escapeHtml(e.organizer)}</p>`:''}${e.website?`<a class="button button--primary button--wide" href="${escapeHtml(e.website)}" target="_blank" rel="noopener">Перейти к регистрации <span>↗</span></a>`:''}`;modal.showModal()}
function populateRegions(){const select=el<HTMLSelectElement>('#region-select');[...regionsById.values()].sort((a,b)=>a.name.localeCompare(b.name,'ru')).forEach(region=>select.add(new Option(region.name,region.id)))}
function openSuggest(){const modal=el<HTMLDialogElement>('#suggest-modal');if(selectedId)el<HTMLSelectElement>('#region-select').value=selectedId;modal.showModal()}

function pointerFrom(clientX:number,clientY:number){const b=renderer.domElement.getBoundingClientRect();pointer.set((clientX-b.left)/b.width*2-1,-((clientY-b.top)/b.height*2-1))}
function getWorldPoint(x:number,y:number){pointerFrom(x,y);raycaster.setFromCamera(pointer,camera);return raycaster.ray.intersectPlane(mapPlane,new THREE.Vector3())}
function intersect(event:PointerEvent){if(!ready)return null;pointerFrom(event.clientX,event.clientY);raycaster.setFromCamera(pointer,camera);return raycaster.intersectObjects(meshes,false)[0]?.object as RegionMesh|undefined}
function resize(){const {width,height}=stage.getBoundingClientRect();if(!width||!height)return;camera.aspect=width/height;camera.updateProjectionMatrix();renderer.setSize(width,height,false)}
new ResizeObserver(resize).observe(stage);
stage.addEventListener('wheel',e=>{e.preventDefault();setZoom(targetZoom*Math.exp(-e.deltaY*.00125),getWorldPoint(e.clientX,e.clientY))},{passive:false});
stage.addEventListener('pointermove',e=>{if(pointerDown&&panAnchor){if(pointerStart.distanceTo(new THREE.Vector2(e.clientX,e.clientY))>4)panning=true;if(panning){const current=getWorldPoint(e.clientX,e.clientY);if(current){targetPosition.add(panAnchor.clone().sub(current));panAnchor=current}stage.classList.add('is-dragging')}return}const id=intersect(e)?.userData.region.id??null;if(id!==hoveredId){hoveredId=id;stage.classList.toggle('is-hovering',!!id);renderSelection()}});
stage.addEventListener('pointerdown',e=>{if(e.button!==0)return;pointerDown=true;panning=false;pointerStart.set(e.clientX,e.clientY);panAnchor=getWorldPoint(e.clientX,e.clientY);stage.setPointerCapture(e.pointerId)});
stage.addEventListener('pointerup',e=>{pointerDown=false;stage.classList.remove('is-dragging');if(stage.hasPointerCapture(e.pointerId))stage.releasePointerCapture(e.pointerId);if(!panning){const hit=intersect(e);if(hit){selectRegion(hit.userData.region.id);focusRegion(hit.userData.region.id)}}panAnchor=null});
stage.addEventListener('pointerleave',()=>{if(!pointerDown){hoveredId=null;renderSelection()}});
el('#zoom-in').addEventListener('click',()=>setZoom(targetZoom*1.2,getWorldPoint(innerWidth/2,innerHeight/2)));el('#zoom-out').addEventListener('click',()=>setZoom(targetZoom/1.2,getWorldPoint(innerWidth/2,innerHeight/2)));el('#zoom-reset').addEventListener('click',resetViewport);
el('#panel-close').addEventListener('click',event=>{event.preventDefault();event.stopPropagation();closeRegionPanel()});el('#suggest-open').addEventListener('click',openSuggest);document.querySelectorAll<HTMLElement>('[data-close-dialog]').forEach(button=>button.addEventListener('click',()=>button.closest('dialog')?.close()));document.querySelectorAll<HTMLDialogElement>('dialog').forEach(dialog=>dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()}));document.addEventListener('keydown',event=>{if(event.key==='Escape'&&panel.classList.contains('is-open')&&!document.querySelector('dialog[open]'))closeRegionPanel()});
const suggestForm=el<HTMLFormElement>('#suggest-form');
suggestForm.addEventListener('submit',async event=>{event.preventDefault();const status=el('#form-status'),button=suggestForm.querySelector<HTMLButtonElement>('button[type="submit"]')!;status.textContent='Отправляем…';button.disabled=true;const payload=Object.fromEntries(new FormData(suggestForm));payload.startsAt=new Date(String(payload.startsAt)).toISOString();if(payload.endsAt)payload.endsAt=new Date(String(payload.endsAt)).toISOString();try{const response=await fetch('/api/submissions/',{method:'POST',headers:{'Content-Type':'application/json','X-CSRFToken':decodeURIComponent(getCookie('csrftoken'))},body:JSON.stringify(payload)}),data=await response.json();if(!response.ok)throw Error(Object.values(data.errors??{}).flat().join(' '));status.textContent=data.message;status.className='form-status is-success';suggestForm.reset();setTimeout(()=>el<HTMLDialogElement>('#suggest-modal').close(),1500)}catch(error){status.textContent=error instanceof Error?error.message:'Не удалось отправить форму';status.className='form-status is-error'}finally{button.disabled=false}});

resize();void Promise.all([loadMap(),loadEvents()]);
let lastFrame=0;
function animate(time=0){requestAnimationFrame(animate);if(document.hidden)return;const moving=pointerDown||Math.abs(zoom-targetZoom)>.001||Math.abs(mapViewport.position.x-targetPosition.x)>.001||Math.abs(mapViewport.position.y-targetPosition.y)>.001||meshes.some(mesh=>Math.abs(mesh.position.z-mesh.userData.targetLift)>.001);const frameInterval=moving?(compactDevice?33:16):200;if(time-lastFrame<frameInterval)return;const delta=Math.min((time-lastFrame)/1000,.05)||1/30;lastFrame=time;zoom=reduceMotion?targetZoom:THREE.MathUtils.damp(zoom,targetZoom,12,delta);mapViewport.scale.setScalar(zoom);mapViewport.position.x=reduceMotion?targetPosition.x:THREE.MathUtils.damp(mapViewport.position.x,targetPosition.x,12,delta);mapViewport.position.y=reduceMotion?targetPosition.y:THREE.MathUtils.damp(mapViewport.position.y,targetPosition.y,12,delta);meshes.forEach(mesh=>mesh.position.z=reduceMotion?mesh.userData.targetLift:THREE.MathUtils.damp(mesh.position.z,mesh.userData.targetLift,15,delta));renderer.render(scene,camera);positionMarkers()}animate();
